# Generated by Django 5.2.11 on 2026-02-24 23:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cargo', models.CharField(max_length=255, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoItemAvaliacaoDesempenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensao', models.CharField(choices=[('Comportamento', 'Comportamento'), ('Entregas', 'Entregas'), ('Trabalho em equipe', 'Trabalho em equipe')], max_length=40, verbose_name='Dimensao')),
                ('tipo_item_avaliacao_desempenho', models.CharField(max_length=255, verbose_name='Tipo de item')),
                ('descricao', models.TextField(verbose_name='Descricao')),
            ],
            options={
                'verbose_name': 'Tipo de item de avaliacao',
                'verbose_name_plural': 'Tipos de itens de avaliacoes',
                'ordering': ['dimensao', 'tipo_item_avaliacao_desempenho'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoDesempenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_competencia', models.DateField(verbose_name='Mes de competencia')),
                ('status_avaliacao', models.CharField(choices=[('Criada', 'Criada'), ('Em elaboracao', 'Em elaboracao'), ('Em avaliacao', 'Em alvaiacao'), ('Concluida', 'Concluida')], default='Criada', max_length=30, verbose_name='Status')),
                ('sugestoes_supervisor', models.TextField(blank=True, null=True, verbose_name='Sugestoes do supervisor')),
                ('observacoes_avaliado', models.TextField(blank=True, null=True, verbose_name='Observacoes do avaliado')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes', to='avaliacao.colaborador', verbose_name='Colaborador')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes_supervisonadas', to='avaliacao.colaborador', verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'Avaliacao de desempenho',
                'verbose_name_plural': 'Avaliacao de desempenhos',
                'ordering': ['-mes_competencia', 'colaborador__nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemAvaliacaoDesempenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nota')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observacoes')),
                ('avaliacao_desempenho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='avaliacao.avaliacaodesempenho', verbose_name='Avaliacao de desempenho')),
                ('tipo_item_avaliacao_desempenho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avaliacao.tipoitemavaliacaodesempenho', verbose_name='Tipo de item')),
            ],
            options={
                'verbose_name': 'Item de avaliacao',
                'verbose_name_plural': 'Itens de avaliacao',
                'ordering': ['tipo_item_avaliacao_desempenho__dimensao'],
            },
        ),
        migrations.AddConstraint(
            model_name='avaliacaodesempenho',
            constraint=models.UniqueConstraint(fields=('colaborador', 'mes_competencia'), name='unique_colaborador_mes_competencia'),
        ),
        migrations.AddConstraint(
            model_name='itemavaliacaodesempenho',
            constraint=models.CheckConstraint(condition=models.Q(('nota__isnull', True), models.Q(('nota__gte', 1), ('nota__lte', 5)), _connector='OR'), name='nota_item_entre_1_e_5'),
        ),
    ]
